
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action OpenAction1;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Action preferencesAction;
	
	private global::Gtk.Action connectAction;
	
	private global::Gtk.Action disconnectAction;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Toolbar toolbar1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView consoleTextView;
	
	private global::Gtk.Statusbar statusbar1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VSeparator vseparator3;
	
	private global::Gtk.Label status;
	
	private global::Gtk.VSeparator vseparator2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label COM;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.Label Baudrate;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.OpenAction1 = new global::Gtk.Action ("OpenAction1", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction1, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", null, null, "gtk-preferences");
		w1.Add (this.preferencesAction, null);
		this.connectAction = new global::Gtk.Action ("connectAction", null, null, "gtk-connect");
		w1.Add (this.connectAction, null);
		this.disconnectAction = new global::Gtk.Action ("disconnectAction", null, null, "gtk-disconnect");
		w1.Add (this.disconnectAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MONO TEST");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='preferencesAction' action='preferencesAction'/><toolitem name='connectAction' action='connectAction'/><toolitem name='disconnectAction' action='disconnectAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox4.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.consoleTextView = new global::Gtk.TextView ();
		this.consoleTextView.CanFocus = true;
		this.consoleTextView.Name = "consoleTextView";
		this.GtkScrolledWindow.Add (this.consoleTextView);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w4.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator ();
		this.vseparator3.Name = "vseparator3";
		this.hbox3.Add (this.vseparator3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.status = new global::Gtk.Label ();
		this.status.Name = "status";
		this.status.LabelProp = global::Mono.Unix.Catalog.GetString ("status");
		this.hbox3.Add (this.status);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.status]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator ();
		this.vseparator2.Name = "vseparator2";
		this.hbox3.Add (this.vseparator2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator2]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.statusbar1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.hbox3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.COM = new global::Gtk.Label ();
		this.COM.Name = "COM";
		this.COM.LabelProp = global::Mono.Unix.Catalog.GetString ("COM");
		this.hbox2.Add (this.COM);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.COM]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.hbox2.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Baudrate = new global::Gtk.Label ();
		this.Baudrate.Name = "Baudrate";
		this.Baudrate.LabelProp = global::Mono.Unix.Catalog.GetString ("Baudrate");
		this.hbox2.Add (this.Baudrate);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.Baudrate]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.statusbar1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.hbox2]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox4.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.statusbar1]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 924;
		this.DefaultHeight = 807;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenAction1.Activated += new global::System.EventHandler (this.OnOpenAction1Activated);
		this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
	}
}
